[pytest]
# Default execution options
addopts =
    -v
    --browser=chromium
    --headed
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --alluredir=reports/allure-results
    --reruns 2
    --reruns-delay 1

# Test Discovery
# Directories to search for testcases
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Custom Markers
markers =
    smoke: Smoke test cases
    sanity: Sanity test cases
    regression: Regression test cases
    api: API test cases

# Enable console logging output during test runs
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

# Ignore Warnings
filterwarnings =
    ignore::DeprecationWarning